Object.defineProperty(globalThis, 'IS_SERVER', {
  value: true,
  writable: false, // 値を変更不可にする
  configurable: false, // 再定義を防ぐ
})

// https://firebase.google.com/docs/functions/typescript
import { setGlobalOptions } from 'firebase-functions/v2/options'
import { initializeApp } from 'firebase-admin/app'

initializeApp()
setGlobalOptions({ region: 'asia-northeast1' })

// ES module 形式の import は並列読み込みのため、initializeApp 等の呼び出しが先に行われることを保証できない
// そのため、ここでは 動的 import を使い、静的 import より後に実行されることを保証する
/* prettier-ignore */ // 各行とファイルを対応させるため
export const {
  getInvitationUrlForCommunityManager, acceptInvitationForCommunityManager,
  sendTestLetter,
  handleEventOgpRequest, handleCommunityOgpRequest, handleSitemapRequest,
  communityAdded, communityContact,
  createStripeCheckoutSession, stripeWebhook, cancelOrders,
  eventInformation, eventInformationPreview,
  shopStatusChanged,
  onEventChanged,
  onShopReservationChanged,
  pollingTask,
  requestEmailLogin, confirmEmailLogin, requestEmailRegistration, confirmEmailRegistration, requestEmailChange, confirmEmailChange, updateProfileFromProviders,
  deleteUserAccount,
  addToCart, removeFromCart, confirmOrder,
  getUserFriends, backfillUserFriends, getUserFriendMeetLog,
  updateUserTags,
  addTagToMyProfile,
  syncMemberTagOnOrderChanged,
  updateEventMemberTags,
  syncUserTagsToEvent,
  eventReceipt,
  eventCopy,
  eventCopyRepeat,
  copyCommunityCoverToEvent,
  eventBillInvoice,
  enterpriseBillInvoice,
  namesprint,
  updateEventMenus,
  sendIndividualLetter,
  generateUserImageThumbnail,
  cancelEvent,
  reportClientError,
  onCommunityMemberWritten,
  getUserProfilePreview, getUserFoods, backfillUserProfileCounts,
  log_event_status,
  flyer,
  slackbot,
  slackEventNotification,
  slackOrderNotification,
  broadcast_event_message_request,
  line_event_information,
  createEnterprise,
  getEnterpriseByDomain,
  requestEnterpriseEmailLogin,
  confirmEnterpriseEmailLogin,
  logEnterpriseLogout,
  createEnterpriseMembers,
  getEnterpriseMembers,
  disableEnterpriseMember,
  enableEnterpriseMember,
  updateEnterpriseMember,
  updateEnterpriseRole,
  updateEnterpriseSettings,
  updateEnterpriseSubsidySettings,
  getEnterpriseCommunities,
  createEnterpriseCommunities,
  getInvitationUrlForEnterpriseCommunityManager,
  acceptInvitationForEnterpriseCommunityManager,
  onChatMessageCreated,
  onChatReactionWritten,
  onEventArchived,
  recallChatMessage,
  getDashboardMonthlyData,
  getDashboardMemberData,
  getEnterpriseAuditLogs,
  captureEnterpriseBillingSnapshots,
  recaptureEnterpriseBillingSnapshot,
  firestoreExportDaily, firestoreExportWeekly, firestoreExportMonthly,
  storageBackupDaily, storageBackupWeekly, storageBackupMonthly,
  backupRetentionCleanup,
} = Object.assign({}, ...(await Promise.all([
  import('./communityManager.js'),
  import('./letter.js'),
  import('./ogpRequest.js'),
  import('./sitemapRequest.js'),
  import('./communityMail.js'),
  import('./stripe.js'), import('./stripeWebhook.js'), import('./cancelOrders.js'),
  import('./eventInformationMail.js'),
  import('./shopOpen.js'),
  import('./eventStatusChangeMail.js'),
  import('./eventMenusSnapshot.js'),
  import('./pollingTask.js'),
  import('./user.js'),
  import('./deleteUserAccount.js'),
  import('./eventReceipt.js'),
  import('./eventCopy.js'),
  import('./eventCopyRepeat.js'),
  import('./copyCommunityCoverToEvent.js'),
  import('./eventBillInvoice.js'),
  import('./enterpriseBillInvoice.js'),
  import('./namesPrint.js'),
  import('./eventMenusSelection.js'),
  import('./userImage.js'),
  import('./memberOrders.js'),
  import('./eventCancellation.js'),
  import('./clientErrorReport.js'),
  import('./userFriends.js'),
  import('./communityMemberCountsTrigger.js'),
  import('./userProfile.js'),
  import('./userTags.js'),
  import('./eventLog.js'),
  import('./flyer.js'),
  import('./slackbot.js'),
  import('./slackEventNotification.js'),
  import('./slackOrderNotification.js'),
  import('./lineBroadcast.js'),
  import('./enterprise/onboarding.js'),
  import('./enterprise/auth.js'),
  import('./enterprise/logout.js'),
  import('./enterprise/members.js'),
  import('./enterprise/role.js'),
  import('./enterprise/settings.js'),
  import('./enterprise/subsidySettings.js'),
  import('./enterprise/community.js'),
  import('./enterprise/communityManager.js'),
  import('./onChatMessageCreated.js'),
  import('./onChatReactionWritten.js'),
  import('./onEventArchived.js'),
  import('./recallChatMessage.js'),
  import('./enterprise/dashboard.js'),
  import('./enterprise/auditLogs.js'),
  import('./enterprise/billingSnapshots.js'),
  import('./backup/scheduled.js'),
])))
