import { Timestamp } from 'firebase/firestore'

export const GENRE_ARRAY = [
  '弁当',
  '丼もの',
  'おにぎり',
  '和食',
  '寿司',
  '魚介料理',
  '海鮮料理',
  '天ぷら',
  '揚げ物',
  'そば',
  'うどん',
  '麺類',
  'うなぎ・どじょう・あなご',
  '焼鳥',
  '串焼',
  '鳥料理',
  'すき焼き',
  'しゃぶしゃぶ',
  'おでん',
  'お好み焼き',
  'たこ焼き',
  '日本料理',
  '郷土料理',
  'ステーキ',
  'ハンバーグ',
  '鉄板焼き',
  'パスタ',
  'ピザ',
  'ハンバーガー',
  '洋食',
  '欧風料理',
  'フレンチ',
  'イタリアン',
  'スペイン料理',
  '西洋各国料理',
  '中華料理',
  '餃子',
  '肉まん',
  '中華粥',
  '中華麺',
  '韓国料理',
  '東南アジア料理',
  '南アジア料理',
  '西アジア料理',
  '中南米料理',
  'アフリカ料理',
  'アジア・エスニック',
  'カレーライス',
  '欧風カレー',
  'インドカレー',
  'スパイスカレー',
  'タイカレー',
  'スープカレー',
  'カレー',
  '焼肉',
  'ホルモン',
  'ジンギスカン',
  'ちゃんこ鍋',
  'うどんすき',
  'もつ鍋',
  '水炊き',
  'ちりとり鍋・てっちゃん鍋',
  '中国鍋・火鍋',
  '韓国鍋',
  'タイスキ',
  '鍋',
  '居酒屋',
  'ダイニングバー',
  '創作料理',
  'イノベーティブ・フュージョン',
  '無国籍料理',
  'ファミレス',
  'レストラン',
  '自然食',
  '薬膳',
  'ラーメン',
  '油そば',
  '台湾まぜそば',
  '汁なし担々麺',
  'つけ麺',
  'カフェ',
  '喫茶店',
  'コーヒー専門店',
  '紅茶専門店',
  '中国茶専門店',
  '日本茶専門店',
  'パン',
  'サンドイッチ',
  'ベーグル',
  '洋菓子',
  '和菓子・甘味処',
  '中華菓子',
  'スイーツ',
  '低糖質',
  'キッチンカー',
  'キムチ',
  '焼き芋',
  'その他',
] as const

export class Shop {
  // class member は基本的にキャメルケースしているが、
  // 以前の仕様で firebase のフィールド名と揃えていたため、そのままスネークケースを採用
  constructor(
    public partner_id: string,
    public shop_id: string | null = null,
    public shop_name: string = '',
    public shop_image_url: string | null = null,
    public shop_description: string = '',
    public shop_url: string = '',
    public shop_postcode: string = '',
    public shop_address: string = '',
    public shop_address_latitude: number = 35.6852,
    public shop_address_longitude: number = 139.7528,
    public shop_phone: string = '',
    public shop_range_min_orders: { range: number | null; min_orders: number | null }[] = [
      { range: null, min_orders: null },
      { range: null, min_orders: null },
      { range: null, min_orders: null },
      { range: null, min_orders: null },
      { range: null, min_orders: null },
    ],
    public min_orders_on_spot: number = 30,
    public createdAt: Timestamp = Timestamp.now(),
    public updatedAt: Timestamp = Timestamp.now(),
    public shop_genre: (typeof GENRE_ARRAY)[number] = 'その他',
    public shop_time: {
      is_open: boolean
      time_start: string
      time_end: string
      time_start2: string
      time_end2: string
    }[] = [
      { is_open: true, time_start: '6:00', time_end: '23:00', time_start2: '', time_end2: '' },
      { is_open: true, time_start: '6:00', time_end: '23:00', time_start2: '', time_end2: '' },
      { is_open: true, time_start: '6:00', time_end: '23:00', time_start2: '', time_end2: '' },
      { is_open: true, time_start: '6:00', time_end: '23:00', time_start2: '', time_end2: '' },
      { is_open: true, time_start: '6:00', time_end: '23:00', time_start2: '', time_end2: '' },
      { is_open: true, time_start: '6:00', time_end: '23:00', time_start2: '', time_end2: '' },
      { is_open: true, time_start: '6:00', time_end: '23:00', time_start2: '', time_end2: '' },
    ],
    public is_approved: boolean = false,
    public is_open: boolean = false,
    public shop_deadline_datetime: {
      days_before: number
      time: number
    } = {
      days_before: 1,
      time: 53100000,
    },
    public shop_url_facebook: string = '',
    public shop_url_twitter: string = '',
    public shop_url_instagram: string = '',
    public shop_email: string = '',
    public shop_email_sub1: string = '',
    public shop_email_sub2: string = '',
    public shop_email_sub3: string = '',
    public community_account?: string,
    public shop_invoice_number?: string,
  ) {}
}
