name: Deploy to Firebase
inputs:
  firebase_tools_version:
    description: 'The version of the Firebase CLI to install'
    required: false
    default: '15.15.0'
  project_id:
    description: 'The Firebase project ID'
    required: true
  args:
    description: 'The arguments to pass to the Firebase CLI'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Firebase CLI
      shell: bash
      # Standalone binary has some issues with deployment, so we use the npm package
      # run: curl -sL https://firebase.tools | bash
      run: npm install -g firebase-tools@${{ inputs.firebase_tools_version }}
    - name: Deploy to Firebase
      shell: bash
      run: firebase --project ${{ inputs.project_id }} deploy ${{ inputs.args }}
