export default [
  {
    id: 1,
    mainImage: new URL('@/assets/images/bokudeli/community_33lab.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: '3x3 Lab ランチ会 😋',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: '3x3 Lab',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区大手町１丁目１−２ 大手門タワー・ENEOSビル 1階',
    max: '20名',
  },
  {
    id: 2,
    mainImage: new URL('@/assets/images/bokudeli/community_sutaha.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'スタハランチ会🏢',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: '3x3 Lab',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区丸の内二丁目1番1号明治安田生命ビル',
    max: '20名',
  },
  {
    id: 3,
    mainImage: new URL('@/assets/images/bokudeli/community_mirailab.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'MIRAI LAB PALETTE ランチ会😘',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'MIRAI LAB PALETTE',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区大手町１丁目６−１ 大手町ビルヂング 2階',
    max: '25名',
  },
  {
    id: 4,
    mainImage: new URL('@/assets/images/bokudeli/community_saai.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'SAAI Wonder Working Community 交流会✨',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'SAAI Wonder Working Community',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区有楽町１丁目１２−１ 新有楽町ビル 10階',
    max: '15名',
  },
  {
    id: 5,
    mainImage: new URL('@/assets/images/bokudeli/community_ship.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'SHIP 品川産業支援交流会 🛳',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'SHIP 品川産業支援交流施設',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都品川区北品川５丁目５−１５ 大崎ブライトコア 3F-4F',
    max: '20名',
  },
  {
    id: 6,
    mainImage: new URL('@/assets/images/bokudeli/community_rokugo.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: '六郷ベース交流会 🛠',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: '六郷ベース',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都大田区南六郷３丁目１０−１６ 六郷BASE',
    max: '10名',
  },
  {
    id: 7,
    mainImage: new URL('@/assets/images/bokudeli/community_qws.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'SHIBUYA QWS ランチ会🍱',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'SHIBUYA QWS',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都渋谷区渋谷２丁目 渋谷スクランブルスクエア 15F',
    max: '25名',
  },
  {
    id: 8,
    mainImage: new URL('@/assets/images/bokudeli/community_andwork.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'andwork渋谷夜会 🎵',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'andwork渋谷',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都渋谷区神南１丁目２０−１３ The Millennials',
    max: '30名',
  },
  {
    id: 9,
    mainImage: new URL('@/assets/images/bokudeli/community_100banch.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: '100banch交流会 ✌️',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: '100banch',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都渋谷区渋谷３丁目２７−１',
    max: '30名',
  },
  {
    id: 10,
    mainImage: new URL('@/assets/images/bokudeli/community_ipark.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: '湘南アイパーク ランチ交流会🏥',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: '湘南アイパーク',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '神奈川県藤沢市村岡東二丁目26番地1',
    max: '15名',
  },
  {
    id: 11,
    mainImage: new URL('@/assets/images/bokudeli/community_fuse.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'FUSE ランチ交流会 👨‍👩‍👧',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'FUSE',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '静岡県浜松市中区鍛冶町１００−１ 中央館 B1F ザザシティ浜松',
    max: '15名',
  },
  {
    id: 12,
    mainImage: new URL('@/assets/images/bokudeli/community_mishima.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'みしま未来研究所 交流会 🎈',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'みしま未来研究所',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '静岡県三島市中央町６−２',
    max: '25名',
  },
  {
    id: 13,
    mainImage: new URL('@/assets/images/bokudeli/community_nakamachi.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: '中富良野町 まちなかオフィス ランチ会🧀',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: '中富良野町 まちなかオフィス',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '北海道空知郡中富良野町南町７−１２',
    max: '25名',
  },
  {
    id: 14,
    mainImage: new URL('@/assets/images/bokudeli/community_niino.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'NINNOランチ会🍚',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'NINNO / ニーノ 新潟県イノベーション拠点施設',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '新潟県新潟市中央区笹口１丁目２−１',
    max: '25名',
  },
  {
    id: 15,
    mainImage: new URL('@/assets/images/bokudeli/community_seesaw.png',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    title: 'seesaw ランチ会😊',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'seesaw 浜松町',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都港区海岸１丁目４−２２ 8~10F SNビル',
    max: '20名',
  },
  {
    id: 16,
    mainImage: new URL('@/assets/images/bokudeli/event_ex_01.png',import.meta.url).href,
    category: 'sales-automation',
    characterSize: '400',
    title: '8周年祭り ランチ会👩🏻‍💻',
    desc: 'There is perhaps no better demonstration of the folly of image of our tiny world.',
    community: 'DMM.make AKIBA',
    shop: 'トゥッカーノグリル',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 17,
    mainImage: new URL('@/assets/images/bokudeli/event_ex_02.png',import.meta.url).href,
    category: 'marketing-automation',
    characterSize: '400',
    title: 'つながる交流会 🚀',
    desc: 'Look again at that dot. That’s here. That’s home. That’s us. On it everyone you love.',
    shop: '御徒町天ぷら・天正',
    community: 'DMM.make AKIBA',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 18,
    mainImage: new URL('@/assets/images/bokudeli/event_ex_03.png',import.meta.url).href,
    category: 'api-questions',
    characterSize: '400',
    title: '第30回 ぼくデリ会 😋',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    community: 'DMM.make AKIBA',
    shop: 'トゥッカーノグリル',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 19,
    mainImage: new URL('@/assets/images/bokudeli/event_ex_04.png',import.meta.url).href,
    category: 'email-marketing',
    characterSize: '400',
    title: '会員勉強会 🎮',
    desc: 'There is perhaps no better demonstration of the folly of human conceits.',
    community: 'DMM.make AKIBA',
    shop: '御徒町天ぷら・天正',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
]