export default [
  {
    id: 1,
    character: new URL(
      '@/assets/images/bokudeli/event_ex_01.png',
      import.meta.url,
    ).href,
    title: '8周年祭り ランチ会👩🏻‍💻',
    desc: 'There is perhaps no better demonstration of the folly of image of our tiny world.',
    community: 'DMM.make AKIBA',
    shop: 'トゥッカーノグリル',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 2,
    character: new URL(
      '@/assets/images/bokudeli/event_ex_02.png',
      import.meta.url,
    ).href,
    title: 'つながる交流会 🚀',
    desc: 'Look again at that dot. That’s here. That’s home. That’s us. On it everyone you love.',
    shop: '御徒町天ぷら・天正',
    community: 'DMM.make AKIBA',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 3,
    character: new URL(
      '@/assets/images/bokudeli/event_ex_03.png',
      import.meta.url,
    ).href,
    title: '第30回 ぼくデリ会 😋',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    community: 'DMM.make AKIBA',
    shop: 'トゥッカーノグリル',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 4,
    character: new URL(
      '@/assets/images/bokudeli/event_ex_04.png',
      import.meta.url,
    ).href,
    title: '会員勉強会 🎮',
    desc: 'There is perhaps no better demonstration of the folly of human conceits.',
    community: 'DMM.make AKIBA',
    shop: '御徒町天ぷら・天正',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 5,
    character: new URL(
      '@/assets/images/bokudeli/event_ex_02.png',
      import.meta.url,
    ).href,
    title: 'つながる交流会 🤩',
    desc: 'It has been said that astronomy is a humbling and character experience.',
    community: 'DMM.make AKIBA',
    shop: '御徒町天ぷら・天正',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 6,
    character: new URL(
      '@/assets/images/bokudeli/event_ex_01.png',
      import.meta.url,
    ).href,
    title: '8周年祭り ランチ会 🤟🏻',
    desc: 'Competent means we will never take anything for granted.',
    community: 'DMM.make AKIBA',
    shop: '御徒町天ぷら・天正',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 7,
    character: new URL(
      '@/assets/images/bokudeli/event_ex_01.png',
      import.meta.url,
    ).href,
    title: '8周年祭り ランチ会 🤟🏻',
    desc: 'Competent means we will never take anything for granted.',
    community: 'DMM.make AKIBA',
    shop: '御徒町天ぷら・天正',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
  {
    id: 8,
    character: new URL(
      '@/assets/images/bokudeli/event_ex_01.png',
      import.meta.url,
    ).href,
    title: '8周年祭り ランチ会 🤟🏻',
    desc: 'Competent means we will never take anything for granted.',
    shop: '御徒町天ぷら・天正',
    community: 'DMM.make AKIBA',
    orderDate: '2022/12/14(水曜日) 23:00',
    eventDate: '2022/12/15(木曜日) 13:00',
    place: '東京都千代田区神田練塀町3 富士ソフト秋葉原ビル12F DMM.makeAKIBA',
    max: '10名',
  },
];
