export default [
  {
    menuImage: new URL('@/assets/images/bokudeli/menu_ex_01.jpg',import.meta.url).href,
    category: 'sales-automation',
    characterSize: '400',
    menu: 'チキンガレット丼',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    shop: 'トゥッカーノグリル',
    price: '1200',
  },
  {
    menuImage: new URL('@/assets/images/bokudeli/menu_ex_02.jpg',import.meta.url).href,
    category: 'marketing-automation',
    characterSize: '400',
    menu: 'メガ丼',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    shop: 'トゥッカーノグリル',
    price: '1500',
  },
  {
    menuImage: new URL('@/assets/images/bokudeli/menu_ex_03.jpg',import.meta.url).href,
    category: 'api-questions',
    characterSize: '400',
    menu: 'ローストポーク丼',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    shop: 'トゥッカーノグリル',
    price: '800',
  },
  {
    menuImage: new URL('@/assets/images/bokudeli/menu_ex_04.jpg',import.meta.url).href,
    category: 'email-marketing',
    characterSize: '400',
    menu: '豚バラ丼',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    shop: 'トゥッカーノグリル',
    price: '800',
  },
  {
    menuImage: new URL('@/assets/images/bokudeli/menu_ex_05.jpg',import.meta.url).href,
    category: 'personalization',
    characterSize: '400',
    menu: '牛ステーキ丼',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    shop: 'トゥッカーノグリル',
    price: '1000',
  },
  {
    menuImage: new URL('@/assets/images/bokudeli/menu_ex_06.jpg',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    menu: '牛スジ煮込み丼',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    shop: 'トゥッカーノグリル',
    price: '1100',
  },
  {
    menuImage: new URL('@/assets/images/bokudeli/menu_ex_01.jpg',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    menu: 'チキンガレット丼',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    shop: 'トゥッカーノグリル',
    price: '1000',
  },
  {
    menuImage: new URL('@/assets/images/bokudeli/menu_ex_01.jpg',import.meta.url).href,
    category: 'demand-generation',
    characterSize: '400',
    menu: 'チキンガレット丼',
    desc: 'Every hero and coward, every creator and destroyer of civilization.',
    shop: 'トゥッカーノグリル',
    price: '1000',
  },
]
