/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/c/[communityId]/': RouteRecordInfo<'/c/[communityId]/', '/c/:communityId', { communityId: ParamValue<true> }, { communityId: ParamValue<false> }>,
    '/c/[communityId]/e/[eventId]/': RouteRecordInfo<'/c/[communityId]/e/[eventId]/', '/c/:communityId/e/:eventId', { communityId: ParamValue<true>, eventId: ParamValue<true> }, { communityId: ParamValue<false>, eventId: ParamValue<false> }>,
    '/c/[communityId]/e/[eventId]/members': RouteRecordInfo<'/c/[communityId]/e/[eventId]/members', '/c/:communityId/e/:eventId/members', { communityId: ParamValue<true>, eventId: ParamValue<true> }, { communityId: ParamValue<false>, eventId: ParamValue<false> }>,
    '/c/[communityId]/invites': RouteRecordInfo<'/c/[communityId]/invites', '/c/:communityId/invites', { communityId: ParamValue<true> }, { communityId: ParamValue<false> }>,
    '/cart': RouteRecordInfo<'/cart', '/cart', Record<never, never>, Record<never, never>>,
    '/communitylist/': RouteRecordInfo<'/communitylist/', '/communitylist', Record<never, never>, Record<never, never>>,
    '/mypage': RouteRecordInfo<'/mypage', '/mypage', Record<never, never>, Record<never, never>>,
    '/u/[userId]': RouteRecordInfo<'/u/[userId]', '/u/:userId', { userId: ParamValue<true> }, { userId: ParamValue<false> }>,
  }
}
