/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[[...error]]': RouteRecordInfo<'/[[...error]]', '/:error(.*)?', { error?: ParamValueZeroOrOne<true> }, { error?: ParamValueZeroOrOne<false> }>,
    '/c/[communityId]/': RouteRecordInfo<'/c/[communityId]/', '/c/:communityId', { communityId: ParamValue<true> }, { communityId: ParamValue<false> }>,
    '/c/[communityId]/e/[eventId]/': RouteRecordInfo<'/c/[communityId]/e/[eventId]/', '/c/:communityId/e/:eventId', { communityId: ParamValue<true>, eventId: ParamValue<true> }, { communityId: ParamValue<false>, eventId: ParamValue<false> }>,
    '/c/[communityId]/e/[eventId]/members': RouteRecordInfo<'/c/[communityId]/e/[eventId]/members', '/c/:communityId/e/:eventId/members', { communityId: ParamValue<true>, eventId: ParamValue<true> }, { communityId: ParamValue<false>, eventId: ParamValue<false> }>,
    '/c/[communityId]/invites': RouteRecordInfo<'/c/[communityId]/invites', '/c/:communityId/invites', { communityId: ParamValue<true> }, { communityId: ParamValue<false> }>,
    '/cart': RouteRecordInfo<'/cart', '/cart', Record<never, never>, Record<never, never>>,
    '/communitylist/': RouteRecordInfo<'/communitylist/', '/communitylist', Record<never, never>, Record<never, never>>,
    '/flyer': RouteRecordInfo<'/flyer', '/flyer', Record<never, never>, Record<never, never>>,
    '/invoice': RouteRecordInfo<'/invoice', '/invoice', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/manage/': RouteRecordInfo<'/manage/', '/manage', Record<never, never>, Record<never, never>>,
    '/manage/community/': RouteRecordInfo<'/manage/community/', '/manage/community', Record<never, never>, Record<never, never>>,
    '/manage/community/[communityAccount]/': RouteRecordInfo<'/manage/community/[communityAccount]/', '/manage/community/:communityAccount', { communityAccount: ParamValue<true> }, { communityAccount: ParamValue<false> }>,
    '/manage/community/[communityAccount]/[tab]': RouteRecordInfo<'/manage/community/[communityAccount]/[tab]', '/manage/community/:communityAccount/:tab', { communityAccount: ParamValue<true>, tab: ParamValue<true> }, { communityAccount: ParamValue<false>, tab: ParamValue<false> }>,
    '/manage/community/[communityAccount]/newevent': RouteRecordInfo<'/manage/community/[communityAccount]/newevent', '/manage/community/:communityAccount/newevent', { communityAccount: ParamValue<true> }, { communityAccount: ParamValue<false> }>,
    '/manage/event/': RouteRecordInfo<'/manage/event/', '/manage/event', Record<never, never>, Record<never, never>>,
    '/manage/event/[eventId]/': RouteRecordInfo<'/manage/event/[eventId]/', '/manage/event/:eventId', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    '/manage/event/[eventId]/[tab]': RouteRecordInfo<'/manage/event/[eventId]/[tab]', '/manage/event/:eventId/:tab', { eventId: ParamValue<true>, tab: ParamValue<true> }, { eventId: ParamValue<false>, tab: ParamValue<false> }>,
    '/manage/event/[eventId]/invoice': RouteRecordInfo<'/manage/event/[eventId]/invoice', '/manage/event/:eventId/invoice', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    '/manage/newcommunity': RouteRecordInfo<'/manage/newcommunity', '/manage/newcommunity', Record<never, never>, Record<never, never>>,
    '/mypage': RouteRecordInfo<'/mypage', '/mypage', Record<never, never>, Record<never, never>>,
    '/newevent': RouteRecordInfo<'/newevent', '/newevent', Record<never, never>, Record<never, never>>,
    '/pass-code': RouteRecordInfo<'/pass-code', '/pass-code', Record<never, never>, Record<never, never>>,
    '/register/complete': RouteRecordInfo<'/register/complete', '/register/complete', Record<never, never>, Record<never, never>>,
    '/register/email': RouteRecordInfo<'/register/email', '/register/email', Record<never, never>, Record<never, never>>,
    '/u/[userId]': RouteRecordInfo<'/u/[userId]', '/u/:userId', { userId: ParamValue<true> }, { userId: ParamValue<false> }>,
    '/u/profile': RouteRecordInfo<'/u/profile', '/u/profile', Record<never, never>, Record<never, never>>,
  }
}
