name: Deploy admin to production

on:
  push:
    branches:
      - production
    paths:
      - "admin/**"
      - "base/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./admin
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./admin/.node-version
          cache: "yarn"
          cache-dependency-path: ./admin/yarn.lock
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file
        run: |
          echo '${{ vars.ADMIN_ENV }}' | tr -d '\r' > .env
      - name: Build
        run: |
          yarn run build-production
      - name: Deploy to Firebase
        uses: ./.github/actions/deploy
        with:
          project_id: bokudeli-event-dev
          service_key: "${{ secrets.GCLOUD_SERVICE_KEY_BOKUDELI_EVENT_TEST_03CF59E61D6C }}"
          args: "--only hosting:admin"
