name: Deploy functions

on:
  push:
    branches:
      - production
      - development
    paths:
      - 'functions/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - development
          - production

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # push のときだけ GITHUB_REF_NAME を使う（workflow_dispatch のときは inputs.environment を使う）
    # 可読性に欠けるが、うまい手がみつからない
    environment: ${{ github.event_name == 'push' && (github.ref_name == 'production' && 'production' || github.ref_name == 'development' && 'development') || inputs.environment }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
      - name: Install dependencies
        run: |
          npm ci
      - name: Generate .env file
        working-directory: ./functions/default
        run: |
          echo '${{ vars.FUNCTIONS_ENV }}' | tr -d '\r' > .env
      - name: Check Format
        run: |
          npm -w common run format:check
          npm -w functions/default run format:check
      - name: Build
        run: |
          npm -w functions/default run build
      - name: Lint
        run: |
          npm -w common run lint
          npm -w functions/default run lint
      - name: Install dependencies for legacy
        working-directory: ./functions/legacy
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file for legacy
        working-directory: ./functions/legacy
        # secrets は環境変数の書き換えによる事故が頻発したので個々で記述する
        # また、将来的には GCP Secret Manager (defineSecret) を使用し、ここで環境変数に書き出すのはやめる
        run: |
          echo '${{ vars.FUNCTIONS_ENV }}' | tr -d '\r' > .env
          echo 'SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}' >> .env
          echo 'PDF_SERVICES_CLIENT_ID=${{ secrets.PDF_SERVICES_CLIENT_ID }}' >> .env
          echo 'PDF_SERVICES_CLIENT_SECRET=${{ secrets.PDF_SERVICES_CLIENT_SECRET }}' >> .env
      - name: Install Dependencies for shokujii-slackbot
        working-directory: ./functions/shokujii-slackbot
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file to shokujii-slackbot
        working-directory: ./functions/shokujii-slackbot
        run: |
          echo '${{ vars.FUNCTIONS_ENV }}' | tr -d '\r' > .env
          echo 'SLACK_CLIENT_ID=${{ secrets.SLACK_CLIENT_ID }}' >> .env
          echo 'SLACK_CLIENT_SECRET=${{ secrets.SLACK_CLIENT_SECRET }}' >> .env
          echo 'SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}' >> .env
          echo 'SLACK_STATE_SECRET=${{ secrets.SLACK_STATE_SECRET }}' >> .env
      - name: Install Dependencies for shokujii-linebot
        working-directory: ./functions/shokujii-linebot
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file to shokujii-linebot
        working-directory: ./functions/shokujii-linebot
        run: |
          echo '${{ vars.FUNCTIONS_ENV }}' | tr -d '\r' > .env
          echo 'LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}' >> .env
      - name: Deploy to Firebase
        uses: ./.github/actions/deploy
        with:
          project_id: ${{ vars.PROJECT_ID }}
          service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          args: '--only functions'
