name: Deploy functions to development

on:
  push:
    branches:
      - development
    paths:
      - "functions/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./functions/legacy/.node-version
          cache: "yarn"
          cache-dependency-path: |
            ./functions/legacy/yarn.lock
            ./functions/shokujii-slackbot/yarn.lock
      - name: Install dependencies
        working-directory: ./functions/legacy
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file
        working-directory: ./functions/legacy
        run: |
          env_vars=$(echo '${{ secrets.FUNCTIONS_DEVELOPMENT_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
          echo "$env_vars" > .env
      - name: Install Dependencies for shokujii-slackbot
        working-directory: ./functions/shokujii-slackbot
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file to shokujii-slackbot
        working-directory: ./functions/shokujii-slackbot
        run: |
          env_vars=$(echo '${{ secrets.FUNCTIONS_SLACKBOT_DEVELOPMENT_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
          echo "$env_vars" > .env
      - name: Install Dependencies for shokujii-linebot
        working-directory: ./functions/shokujii-linebot
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file to shokujii-linebot
        working-directory: ./functions/shokujii-linebot
        run: |
          env_vars=$(echo '${{ secrets.FUNCTIONS_LINEBOT_DEVELOPMENT_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
          echo "$env_vars" > .env
      - name: Install Dependencies for shokujii-pdf
        working-directory: ./functions/shokujii-pdf
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file to shokujii-pdf
        working-directory: ./functions/shokujii-pdf
        run: |
          env_vars=$(echo '${{ secrets.FUNCTIONS_PDF_DEVELOPMENT_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
          echo "$env_vars" > .env
      - name: Deploy to Firebase
        uses: ./.github/actions/deploy
        with:
          project_id: ${{ vars.PROJECT_ID }}
          service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          args: "--only functions"
