name: Deploy manager for development

on:
  push:
    branches:
      - development
    paths:
      - "manager/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash
        working-directory: ./manager
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./manager/.node-version
          cache: "npm"
          cache-dependency-path: ./manager/package-lock.json
      - name: Generate .env file
        run: |
          echo '${{ vars.MANAGER_ENV }}' | tr -d '\r' > .env
      - name: Build
        run: |
          npm install
          npm run build-development
      - name: Deploy to Firebase
        uses: ./.github/actions/deploy
        with:
          firebase_tools_version: '^12'
          project_id: bokudeli-event-test
          service_key: "${{ secrets.GCLOUD_SERVICE_KEY_BOKUDELI_EVENT_TEST_03CF59E61D6C }}"
          args: "--only hosting:manager"
