name: Deploy curry

on:
  push:
    branches:
      - production
    paths:
      - "curry/**"
      - "base/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: |
          npm install --frozen-lockfile
      - name: Generate .env file
        working-directory: ./curry
        run: |
          echo '${{ vars.CURRY_ENV }}' | tr -d '\r' > .env
      - name: Check Format
        run: |
          npm -w common run format:check
          npm -w base run format:check
          npm -w curry run format:check
      - name: Build
        run: |
          npm -w curry run build
      - name: Lint
        run: |
          npm -w common run lint
          npm -w base run lint
          npm -w curry run lint
      - name: Generate .firebaserc
        run: |
          echo '${{ vars.FIREBASERC }}' > .firebaserc
      - name: Deploy to Firebase
        uses: ./.github/actions/deploy
        with:
          project_id: ${{ vars.PROJECT_ID }}
          service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          args: "--only hosting:curry"
