name: Deploy admin

on:
  push:
    branches:
      - main
    paths:
      - 'admin/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./admin
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: ./admin/.node-version
        cache: 'npm'
        cache-dependency-path: ./admin/package-lock.json
    - name: Generate .env file
      run: |
        env_vars=$(echo '${{ secrets.ADMIN_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
        echo "$env_vars" > .env
    - name: Deploy to Firebase
      run: |
        npm install
        npm run build-development
        npx firebase use bokudeli-event-test
        npx firebase deploy --only hosting:admin
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
