name: Deploy functions to development

on:
  push:
    branches:
      - development
    paths:
      - "functions/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./functions
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./functions/.node-version
          cache: "yarn"
          cache-dependency-path: |
            ./functions/yarn.lock
            ./functions/shokujii-slackbot/yarn.lock
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Install Firebase CLI
        working-directory: .
        run: yarn global add firebase-tools@13.35.1
      - name: Generate .env file
        run: |
          env_vars=$(echo '${{ secrets.FUNCTIONS_DEVELOPMENT_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
          echo "$env_vars" > .env
      - name: Install Dependencies for shokujii-slackbot
        working-directory: ./functions/shokujii-slackbot
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file to shokujii-slackbot
        working-directory: ./functions/shokujii-slackbot
        run: |
          env_vars=$(echo '${{ secrets.FUNCTIONS_SLACKBOT_DEVELOPMENT_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
          echo "$env_vars" > .env
      - name: Install Dependencies for shokujii-linebot
        working-directory: ./functions/shokujii-linebot
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file to shokujii-linebot
        working-directory: ./functions/shokujii-linebot
        run: |
          env_vars=$(echo '${{ secrets.FUNCTIONS_LINEBOT_DEVELOPMENT_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
          echo "$env_vars" > .env
      - name: Install Dependencies for shokujii-pdf
        working-directory: ./functions/shokujii-pdf
        run: |
          yarn install --frozen-lockfile
      - name: Generate .env file to shokujii-pdf
        working-directory: ./functions/shokujii-pdf
        run: |
          env_vars=$(echo '${{ secrets.FUNCTIONS_PDF_DEVELOPMENT_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
          echo "$env_vars" > .env
      # FIREBASE_TOKEN is deprecated, so use GOOGLE_APPLICATION_CREDENTIALS
      - name: Deploy to Firebase
        working-directory: .
        # We may use asyncronous jobs to deploy, so we need to use mktemp instead of a fixed path
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(mktemp)
          echo '${{ secrets.GCLOUD_SERVICE_KEY_BOKUDELI_EVENT_TEST_03CF59E61D6C }}' > $GOOGLE_APPLICATION_CREDENTIALS
          firebase use bokudeli-event-test
          firebase deploy --only functions
          rm $GOOGLE_APPLICATION_CREDENTIALS
