name: Deploy user

on:
  push:
    branches:
      - main
    paths:
      - 'user/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./user
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: ./user/.node-version
        cache: 'yarn'
        cache-dependency-path: ./user/yarn.lock
    - name: Generate .env file
      run: |
        env_vars=$(echo '${{ secrets.USER_ENV_SECRET }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"')
        echo "$env_vars" > .env
    - name: Build
      run: | 
        yarn install --frozen-lockfile
        yarn run build-development
    - name: Deploy
      working-directory: .
      run: |
        npx firebase use bokudeli-event-test
        npx firebase deploy --only hosting:user
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
