name: Deploy manager

on:
  push:
    branches:
      - development
      - production
    paths:
      - 'manager/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - development
          - production

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # push のときだけ GITHUB_REF_NAME を使う（workflow_dispatch のときは inputs.environment を使う）
    # 可読性に欠けるが、うまい手がみつからない
    environment: ${{ github.event_name == 'push' && (github.ref_name == 'production' && 'production' || github.ref_name == 'development' && 'development') || inputs.environment }}
    env:
      # environment の値を動的に取得する方法がないため、再度 env に同じ値を設定する
      # TODO Reusable workflow 等を使用して二重定義を解消する
      ENVIRONMENT: ${{ github.event_name == 'push' && (github.ref_name == 'production' && 'production' || github.ref_name == 'development' && 'development') || inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: ./manager
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ./manager/.node-version
          cache: 'npm'
          cache-dependency-path: ./manager/package-lock.json
      - name: Generate .env file
        run: |
          echo '${{ vars.MANAGER_ENV }}' | tr -d '\r' > .env
      - name: Build
        run: |
          npm install
          npm run build-${ENVIRONMENT}
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash
      - name: Deploy to Firebase
        shell: bash
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(mktemp)
          echo '${{ secrets.GCLOUD_SERVICE_KEY }}' > $GOOGLE_APPLICATION_CREDENTIALS
          firebase use ${{ vars.PROJECT_ID }}
          firebase deploy --only hosting:manager
          rm $GOOGLE_APPLICATION_CREDENTIALS
