name: Deploy firestore to production

on:
  push:
    branches:
      - production
    paths:
      - "firestore.rules"
      - "firestore.indexes.json"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Firebase
        uses: ./.github/actions/deploy
        with:
          project_id: bokudeli-event-dev
          service_key: "${{ secrets.GCLOUD_SERVICE_KEY_BOKUDELI_EVENT_DEV_736E27344811 }}"
          args: "--only firestore:rules"
